---
name: LCFG-Build-VCS
version: 0.1.4
author:
  - 'Stephen Quinney <squinney@inf.ed.ac.uk>'
abstract: LCFG version control infrastructure
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  DateTime: 0
  File::Copy::Recursive: 0.36
  File::HomeDir: 0.58
  IPC::Run: 0
  Moose: 0.57
  perl: 5.6.1
  URI: 0
build_requires:
  Test::More: 0
provides:
  LCFG::Build::VCS:
    file: lib/LCFG/Build/VCS.pm
    version: 0.1.4
  LCFG::Build::VCS::CVS:
    file: lib/LCFG/Build/VCS/CVS.pm
    version: 0.1.4
  LCFG::Build::VCS::None:
    file: lib/LCFG/Build/VCS/None.pm
    version: 0.1.4
  LCFG::Build::VCS::SVN:
    file: lib/LCFG/Build/VCS/SVN.pm
    version: 0.1.4
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
